batch_size: 512
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
<<<<<<< HEAD
loss_type : marginal_triplet
=======
loss_type : nt_xent
>>>>>>> 42d3cd2a976930338a51f1933cd5524557850d6a
model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05

loss:
  m: 0
  use_cosine_similarity: True
