batch_size: 512
epochs: 1
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
loss_type : marginal_triplet
model:
  out_dim: 64
  base_model: "resnet50"

dataset:
  s: 1
  input_shape: (32,32,3)
  num_workers: 0
  valid_size: 0.05

loss:
  m: 1
  use_cosine_similarity: True
